name: Enforce Branch Protection Rules

on:
  push:
    branches:
      - main
      - nrl-rounds-backups
  pull_request:
    branches:
      - main
      - nrl-rounds-backups

jobs:
  protect-branches:
    runs-on: ubuntu-latest
    steps:
    - name: Protect Main and NRL Rounds Backups Branches
      uses: JMShadbury/github-actions-library/branch-protector@v1
      with:
        source_branch: 'nrl-rounds-backups'
        target_branch: 'main'
