name: Merge Dependabot PRs

on:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Pylint
        uses: JMShadbury/github-actions-library/pylint-action@v1
        env:
            GITHUB_WORKSPACE: ${{ github.workspace }} 
      - name: Merge PR
        uses: JMShadbury/github-actions-library/merge-dependabot-action@v1
          
