on:
    workflow_run:
      workflows: ["Main Workflow"]  # Replace with the name of your main workflow
      types:
        - completed
  
  permissions:
    contents: write
    pull-requests: write
  
  jobs:
    auto-merge:
      runs-on: ubuntu-latest
      if: github.event.workflow_run.conclusion == 'success'  # Run only if the main workflow was successful
      steps:
        - name: Auto-merge Dependabot PRs
          uses: actions/github-script@v5
          with:
            script: |
              const prNumber = github.event.workflow_run.pull_requests[0].number;
              const { data: pullRequest } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
              });
  
              if (pullRequest.user.login === 'dependabot[bot]' && pullRequest.mergeable) {
                await github.rest.pulls.merge({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: prNumber,
                });
              }
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  