name: Merge Dependabot PRs

on:
    workflow_run:
      workflows: ["Pylint"]
      types: 
        - completed
    pull_request_target:

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    steps:
      - name: Log Dependabot PR details
        uses: actions/github-script@v5
        with:
          script: |
            console.log(`Dependabot PR detected: ${context.payload.pull_request.html_url}`);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
