on: pull_request_target

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    steps:
      - name: Auto-merge Dependabot PRs
        uses: actions/github-script@v5
        with:
          script: |
            const { pull_request } = context.payload;
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_request.number
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
