name: Auto Merge

on:
  workflow_run:
    workflows: ["Pylint"]  # This should match the name of your Pylint workflow
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push'
    steps:
      - name: Auto-merge Dependabot PRs
        uses: actions/github-script@v5
        with:
          script: |
            const repo = context.repo;
            const prs = await github.rest.pulls.list({
              owner: repo.owner,
              repo: repo.repo,
              state: 'open',
            });

            for (const pr of prs.data) {
              if (pr.user.login === 'dependabot[bot]' && pr.mergeable) {
                await github.rest.pulls.merge({
                  owner: repo.owner,
                  repo: repo.repo,
                  pull_number: pr.number,
                });
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
