name: Deploy DynamoDBStack


permissions:
  id-token: write
  contents: read


on:
  push:
    branches:
      - feature/auto_build


jobs:
  deploy_db_stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.MY_AWS_REGION }}
          role-session-name: "GitHubActions-Deploy-DynamoDbStack"


      - name: Deploy DynamoDB cdk stack
        run: |
          npm install -g aws-cdk
          make deployDynamodb