name: Deploy Container

on:
  push:
    branches: [ "main" ]
    paths:
      - scripts/app/*
      - scripts/app/*/*
      - scripts/app/*/*/*
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    secrets: inherit
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: get latest data
        uses: ./.github/actions/get_data_from_db
      - name: deploy container
        uses: ./.github/actions/deploy_container