name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - application_whitelist/*
      - backend/*
      - backend/*/*

permissions:
  id-token: write
  contents: read 
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: deploy_backend
        uses: ./.github/actions/deploy_backend/action.yml