name: Deploy Backend
on:
  push:
    branches:
      - main
    paths:
      - application_whitelist/*
      - backend/*
      - backend/*/*
permissions:
  id-token: write
  contents: read 
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    secrets: inherit
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: deploy_backend
        uses: ./.github/actions/deploy_backend
        with:
          awsRole: ${{ secrets.AWS_ROLE }}
          awsRegion: ${{ secrets.MY_AWS_REGION }}