name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Run Pylint
        uses: JMShadbury/github-actions-library/pylint-action@v1
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }} 
          
      - name: Upload Pylint Report
        uses: JMShadbury/github-actions-library/upload-artifact-action@v1
        with:
          name: 'nrl-stat-tracker'
          path: '.'
