name: Backup NRL Data

on:
  schedule:
    - cron: '0 0 * * 2'  # Runs at 00:00 every Tuesday
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        ref: nrl-rounds-backups

    - name: Create directories and files
      run: |
          mkdir -p scrape/all_data
          mkdir -p app/ladder
          mkdir -p app/teams
          echo "[]" > app/ladder/ladder_data.json
          while read team; do
            if [ ! -f "app/teams/$team.json" ]; then
              touch "app/teams/$team.json"
            fi
          done < scrape/teams

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Read Current Round
      id: current-round
      run: |
        echo "ROUND_NUMBER=$(cat round.txt)" >> $GITHUB_ENV
        echo "::set-output name=round::$(cat round.txt)"

    - name: Scrape NRL Data
      run: make getData

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v3
      with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GitHubActions
          aws-region: ${{ secrets.AWS_REGION }}

    - name: Run Make Backup
      env:
        BACKUP_PASSWORD: ${{ secrets.BACKUP_PASSWORD }}
        ROUND_NUMBER: ${{ steps.current-round.outputs.round }}
      run: |
        make backup

    - name: Check out a new branch
      run: |
          git checkout -b update-branch-${{ github.run_number }}
          git push --set-upstream origin update-branch-${{ github.run_number }}
      

    - name: Update Round Number
      run: |
          new_round=$((${{ env.ROUND_NUMBER }} + 1))
          echo $new_round > round.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add round.txt
          git commit -m "Update round number to $new_round"
          git push

    - name: Create Pull Request with Label using hub-pr-creator
      uses: JMShadbury/github-actions-library/hub-pr-creator@v1
      with:
        base_branch: 'nrl-rounds-backups'
        head_branch: 'update-branch-${{ github.run_number }}'
        pr_title: 'Update round number to ${{ env.ROUND_NUMBER }}'
        labels: 'automerge'
        github_token: ${{ secrets.GH_PAT }}
        
    - name: Wait for Status checks
      run: |
        sleep 90

    - name: Automerge
      uses: pascalgn/automerge-action@v0.16.2
      env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          MERGE_LABELS: 'automerge'  
          MERGE_METHOD: 'squash'     
          MERGE_COMMIT_MESSAGE: 'auto-merge'
          MERGE_FILTER_AUTHOR: 'github-actions[bot]'   
