name: Backup NRL Data

on:
  schedule:
    - cron: '0 0 * * 2'  # Runs at 00:00 every Tuesday
  workflow_dispatch:

permissions:
  id-token: write
  contents: write


jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        ref: nrl-rounds-backups


    - name: Create directories and files
      run: |
          mkdir -p scrape/all_data
          mkdir -p app/ladder
          echo "[]" > app/ladder/ladder_data.json
          while read team; do
            mkdir -p "scrape/all_data/$team"
            if [ ! -f "app/teams/$team.json" ]; then
              touch "app/teams/$team.json"
            fi
          done < app/teams/teams

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Read Current Round
      id: current-round
      run: |
        echo "ROUND_NUMBER=$(cat round.txt)" >> $GITHUB_ENV
        echo "::set-output name=round::$(cat round.txt)"

    - name: Scrape NRL Data
      run: make getData
    
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v3
      with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GitHubActions
          aws-region: ${{ secrets.AWS_REGION }}

    - name: Run Make Backup
      run: make backup ROUND=${{ env.ROUND_NUMBER }}

    - name: Update Round Number
      if: ${{ steps.current-round.outputs.round < 27 }}
      run: |
        echo $(( ${{ env.ROUND_NUMBER }} + 1 )) > round.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add round.txt
        git commit -m "Update round number to $(( ${{ env.ROUND_NUMBER }} + 1 ))"
        git push origin nrl-rounds-backups

