name: Scrape Teams Data

on:
  push:
    branches: [ "feature/auto_build" ]
                      
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ secrets.MY_AWS_REGION }}  

    - name: Scrape data
      id: scrape-teams
      run: |
        make updateTeams
