name: Scrape Teams Data

on:
  push:
    branches: [ "feature/auto_build" ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}                                  
  ROLE_NAME: ${{ secrets.AWS_ROLE }}
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: $ROLE_NAME
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: $AWS_REGION

    - name: Scrape data
      id: Scraping NRL data
      run: |
        make updateTeams
