name: Update Stats

on:
  schedule:
    - cron: '* 0 * * 4'
  workflow_dispatch:

env:             
  ECS_SERVICE: ${{ secrets.ECR_SERVICE_NAME }}               
  ECS_CLUSTER: ${{ secrets.ECR_CLUSTER_NAME }}              
  CONTAINER_NAME: ${{ secrets.ECR_CONTAINER_NAME }} 

permissions:
  id-token: write
  contents: read 
  
jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
  
  get_credentials:
    name: Get AWS credentials
    runs-on: ubuntu-latest
    environment: production
    needs: [Checkout]
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: ${{ secrets.MY_AWS_REGION }}
        role-session-name: "GitHubActions-Deploy-DynamoDbStack"

  scrape_data:
    name: Scrape Data
    runs-on: ubuntu-latest
    environment: production
    needs: [Get AWS credentials]
    steps:
    - name: Scrape Data
      run: |
        make updateStats
