name: Update Stats
on:
  schedule:
    - cron: '* 0 * * 4'
  workflow_dispatch:
permissions:
  id-token: write
  contents: read 
jobs:
  scrape_data:
    name: scrape
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: scrape_data
      uses: ./.github/actions/scrape_data
      with:
          awsRole: ${{ secrets.AWS_ROLE }}
          awsRegion: ${{ secrets.MY_AWS_REGION }}
  deploy_container:
    needs: scrape_data
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: get_data_from_db
      uses: ./.github/actions/get_data_from_db
      with:
          awsRole: ${{ secrets.AWS_ROLE }}
          awsRegion: ${{ secrets.MY_AWS_REGION }}
    - name: deploy_container
      uses: ./.github/actions/deploy_container
      with:          
          ECR_REPOSITORY: ${{ secrets.ECR_NAME }}      
          ECS_SERVICE: ${{ secrets.ECR_SERVICE_NAME }}               
          ECS_CLUSTER: ${{ secrets.ECR_CLUSTER_NAME }}              
          CONTAINER_NAME: ${{ secrets.ECR_CONTAINER_NAME }} 
          awsRole: ${{ secrets.AWS_ROLE }}
          awsRegion: ${{ secrets.MY_AWS_REGION }}
