name: Update Stats

on:
  schedule:
    - cron: '* 0 * * 4'
  workflow_dispatch:

  workflow_run:
    workflows: ["Deploy Container"]
    type:
      - complete

env:             
  ECS_SERVICE: ${{ secrets.ECR_SERVICE_NAME }}               
  ECS_CLUSTER: ${{ secrets.ECR_CLUSTER_NAME }}              
  CONTAINER_NAME: ${{ secrets.ECR_CONTAINER_NAME }} 

permissions:
  id-token: write
  contents: read 
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: ${{ secrets.MY_AWS_REGION }}
        role-session-name: "GitHubActions-Deploy-DynamoDbStack"

    - name: Scrape Data
      run: |
        make updateStats
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: ${{ secrets.MY_AWS_REGION }}
        role-session-name: "GitHubActions-Deploy-DynamoDbStack"

    - name: Get Data
      run: |
        make getData
